module.exports = {
    raama: '/raama',
    taotlus_login: '/ou/taotlus_login',
    admin: '/admin',
    kasutaja: '/kasutaja',
    juht: '/juht',
    asutused:'/libs/asutused',
    objekt: '/libs/objekt',
    isiku_objekt: '/libs/isiku_objekt',
    leping:'/raama/leping',
    isiku_leping:'/raama/isiku_leping',
    nomenclature: '/libs/nomenclature',
    andmed:'/raama/andmed',
    arv:'/raama/arv',
    isiku_arv:'/raama/isiku_arv',
    smk:'/raama/smk',
    vmk:'/raama/vmk',
    aa:'/ou/aa',
    kassa:'/ou/kassa',
    sorder:'/raama/sorder',
    rekl:'/juht/rekl',
    userid:'/ou/userid',
    kaive_aruanne:'/raama/kaive_aruanne'
};
