module.exports = {
    "Lisa andmed": ['Add data', 'Lisa andmed', 'Добавить показания'],
    "Lisa": ["Add", "Lisa", "Добавить"],
    "Muuda": ["Edit", "Muuda", "Редактировать"],
    "Kustuta": ["Delete", "Kustuta", "Удалить"],
    "Trükk": ["Print", "Trükk", "Печать"],
    "Filter": ["Filter", "Filter", "Фильтр"],
    "Uuenda": ["Refresh", "Uuenda", "Обновить"],
    "Limiit:": ["Limit:", "Limiit:", "Лимит:"],
    "Välju": ["Exit", "Välju", "Выход"],
    "Sisse": ["Login", "Sisse", "Вход"],
    "Juhend": ["Help", "Juhend", "Помощь"],
    "Dokument": ["Document", "Dokument", "Документ"],
    "Kuupäev": ["Date", "Kuupäev", "Дата"],
    "Objekt": ["Object", "Objekt", "Обьект"],
    "Korteriomanik": ["Owner", "Korteriomanik", "Владелец"],
    "raama": ["Accounting", "raama", "Бух.учет"],
    "Aruanned": ["Reports", "Aruanned", "Отчеты"],
    "Käibearuanne": ["Turnover report", "Käibearuanne", "Оборотная ведомость"],
    "Arved koodi järgi": ["Bills", "Arved koodi järgi", "Счета в разрезе услуг"],
    "Dokumendid": ["Documents", "Dokumendid", "Документы"],
    "Lepingud": ["Contracts", "Lepingud", "Договора"],
    "Mõõdukiri andmed": ["Data", "Andmed", "Показания"],
    "Sissemakse korraldused": ["Income orders", "Sissemakse korraldused", "Входящие платежные поручения"],
    "Väljamakse korraldused": ["Outcome orders", "Väljamakse korraldused", "Исходящие платежные поручения"],
    "Sissemakse kassaorder": ["Income cash orders", "Sissemakse kassaorder", "Приходные кассовые ордера"],
    "Väljamakse kassaorder": ["Outcome cash orders", "Väljamakse kassaorder", "Расходные кассовые ордера"],
    "Arved": ["Bills register", "Arved", "Реестр счетов"],
    "Püsiandmed": ["Library", "Püsiandmed", "Справочники"],
    "Kliendid": ["Clients", 'Kliendid', "Клиенты"],
    "Teenused": ["Services", "Teenused", "Справочник услуг"],
    "Objektid": ["Objects", "Objektid", "Обьекты"],
    "Häälestamine": ["Properties", "Häälestamine", "Настройки"],
    "Oma asutuse andmed": ["Base data", "Oma asutuse andmed", "Данные учреждения"],
    "Konfiguratsioon": ["Config", "Konfiguratsioon", "Конфигурация"],
    "Saatja": ["Sender", "Saatja", "Отправитель"],
    "Staatus": ["Status", "Staatus", "Статус"],
    "Number": ["Number", "Number", "Номер"],
    "Asutus": ["Client", "Asutus", "Клиент"],
    "Selgitus": ["Description", "Selgitus", "Описание"],
    "Tähtaeg":["Deadline","Tähtaeg","Срок"],
    "Valitud":["Selected","Valitud","Выбрано"],
    "Valida":["Select","Valitud","Выбрать"],
    "Koosta arved":["Create bill","Koosta arved","Создать счет"],
    "Täitmine":["Execute","Täitmine","Выполнить"],
    "Leping Nr.":["Contract Nr.","Leping Nr.","Договор номер"],
    "Andmed":["Data","Andmed","Показания"],
    "Maksja":["Payer","Maksja","Плательщик"],
    "Arveldus arve":["Account nr.","Arveldus arve","Расчетный счет"],
    "Viite number":["Referance","Viite number","Ссылка"],
    "Maksepäev":["Payment day","Maksepäev","Дата платежа"],
    "Summa":["Summa","Summa","Сумма"],
    "Koosta tagasimakse":["Create return payment","Koosta tagasimakse","Сделать возврат"],
    "Panga VV logid":["Bank statement","Panga VV logid","Выписка из банка"],
    "Saama XML (SEPA) kõik valitud maksed":["Get XML (SEPA) all selected docs","Saama XML (SEPA) kõik valitud maksed","Получить XML (SEPA) всех выделенных платежей"],
    "Nimi":["Name","Nimi","Имя"],
    "Isikukood":["Reg.code","Isikukood","Личный код"],
    "Nimetus":["Name","Nimetus","Наименование"],
    "Aadress":["Address","Aadress","Адрес"],
    "Kood":["Code","Kood","Код"],
    "Omanik":["Owner","Omanik","Собственник"]


}