module.exports = {
    "Lisa andmed": ['Add data', 'Lisa andmed', 'Добавить показания'],
    "Lisa": ["Add", "Lisa", "Добавить"],
    "Muuda": ["Edit", "Muuda", "Редактировать"],
    "Kustuta": ["Delete", "Kustuta", "Удалить"],
    "Trükk": ["Print", "Trükk", "Печать"],
    "Filter": ["Filter", "Filter", "Фильтр"],
    "Uuenda": ["Refresh", "Uuenda", "Обновить"],
    "Save":["Save","Salvesta","Сохранить"],
    "Cancel":["Cancel","Katkesta","Отмена"],
    "Limiit:": ["Limit:", "Limiit:", "Лимит:"],
    "Välju": ["Exit", "Välju", "Выход"],
    "Sisse": ["Login", "Sisse", "Вход"],
    "Juhend": ["Help", "Juhend", "Помощь"],
    "Dokument": ["Document", "Dokument", "Документ"],
    "Kuupäev": ["Date", "Kuupäev", "Дата"],
    "Korr.konto":["Correspondent account","Korr.konto","Кор.счет"],
    "Tunnus":["Indentificator","Tunnus","Признак"],
    "Projekt":["Project","Projekt","Проект"],
    "Objekt": ["Object", "Objekt", "Обьект"],
    "Korteriomanik": ["Owner", "Korteriomanik", "Владелец"],
    "raama": ["Accounting", "raama", "Бух.учет"],
    "Aruanned": ["Reports", "Aruanned", "Отчеты"],
    "Käibearuanne": ["Turnover report", "Käibearuanne", "Оборотная ведомость"],
    "Arved koodi järgi": ["Bills", "Arved koodi järgi", "Счета в разрезе услуг"],
    "Dokumendid": ["Documents", "Dokumendid", "Документы"],
    "Lepingud": ["Contracts", "Lepingud", "Договора"],
    "Mõõdukiri andmed": ["Data", "Andmed", "Показания"],
    "Sissemakse korraldused": ["Income orders", "Sissemakse korraldused", "Входящие платежные поручения"],
    "Väljamakse korraldused": ["Outcome orders", "Väljamakse korraldused", "Исходящие платежные поручения"],
    "Sissemakse kassaorder": ["Income cash orders", "Sissemakse kassaorder", "Приходные кассовые ордера"],
    "Väljamakse kassaorder": ["Outcome cash orders", "Väljamakse kassaorder", "Расходные кассовые ордера"],
    "Arved": ["Bills register", "Arved", "Реестр счетов"],
    "Püsiandmed": ["Library", "Püsiandmed", "Справочники"],
    "Kliendid": ["Clients", 'Kliendid', "Клиенты"],
    "Teenused": ["Services", "Teenused", "Справочник услуг"],
    "Objektid": ["Objects", "Objektid", "Обьекты"],
    "Häälestamine": ["Properties", "Häälestamine", "Настройки"],
    "Oma asutuse andmed": ["Base data", "Oma asutuse andmed", "Данные учреждения"],
    "Konfiguratsioon": ["Config", "Konfiguratsioon", "Конфигурация"],
    "Saatja": ["Sender", "Saatja", "Отправитель"],
    "Staatus": ["Status", "Staatus", "Статус"],
    "Number": ["Number", "Number", "Номер"],
    "Asutus": ["Client", "Asutus", "Клиент"],
    "Selgitus": ["Description", "Selgitus", "Описание"],
    "Tähtaeg": ["Deadline", "Tähtaeg", "Срок"],
    "Hind":["Price","Hind","Цена"],
    "Raha saaja":["Beneficiary","Raha saaja","Получатель"],
    "Kassa":["Cash account","Kassa","Касса"],
    "Arve nr":["Bill nr.","Arve nr.","Счет ном."],
    "Valitud": ["Selected", "Valitud", "Выбрано"],
    "Valida": ["Select", "Valitud", "Выбрать"],
    "Koosta arved": ["Create bill", "Koosta arved", "Создать счет"],
    "Täitmine": ["Execute", "Täitmine", "Выполнить"],
    "Leping Nr.": ["Contract Nr.", "Leping Nr.", "Договор номер"],
    "Andmed": ["Data", "Andmed", "Показания"],
    "Märkused": ["Description", "Märkused", "Примечания"],
    "Korteeriomanik":["Owner","Korteeriomanik","Владелец"],
    "kogus":["Quantity","Kogus","Количество"],
    "Mõõdu andmed":["Data","Mõõdu andmed","Показания"],
    "Eelmise kogus":["Previous quantity","Eelmise kogus","Предыдущее кол-во"],
    "Loggid":["Logs","Loggid","Логи"],
    "Maksja": ["Payer", "Maksja", "Плательщик"],
    "Arveldus arve": ["Account nr.", "Arveldus arve", "Расчетный счет"],
    "Viite number": ["Referance", "Viite number", "Ссылка"],
    "Maksepäev": ["Payment day", "Maksepäev", "Дата платежа"],
    "Käibemaks":["Tax","Käibemaks","Налог с оборота"],
    "Summa": ["Summa", "Summa", "Сумма"],
    "Koosta tagasimakse": ["Create return payment", "Koosta tagasimakse", "Сделать возврат"],
    "Panga VV logid": ["Bank statement", "Panga VV logid", "Выписка из банка"],
    "Saama XML (SEPA) kõik valitud maksed": ["Get XML (SEPA) all selected docs", "Saama XML (SEPA) kõik valitud maksed", "Получить XML (SEPA) всех выделенных платежей"],
    "Nimi": ["Name", "Nimi", "Имя"],
    "Isikukood": ["Reg.code", "Isikukood", "Личный код"],
    "Nimetus": ["Name", "Nimetus", "Наименование"],
    "Aadress": ["Address", "Aadress", "Адрес"],
    "Alus":["Base","Alus","Основание"],
    "Kood": ["Code", "Kood", "Код"],
    "Laadimine...":["Loading...","Laadimine...","Загружаю..."],
    "Omanik": ["Owner", "Omanik", "Собственник"],
    "Tasud": ["Payed", "Tasud", "Оплачен"],
    "Jääk": ["Saldo", "Jääk", "Сальдо"],
    "Trükk kõik valitud arved": ["Print all selected bills", "Trükk kõik valitud arved", "Печать всех выбранных счетов"],
    "Email kõik valitud arved": ["Email all selected bills", "Email kõik valitud arved", "Отправить эл. почтой выбранные счета"],
    "Saada E-Arved (Omniva) kõik valitud arved": ["Send to Omniva all selected bills", "Saada E-Arved (Omniva) kõik valitud arved", "Отправить в Омнива все выбранные счета"],
    "Saama XML e-arved kõik valitud arved": ["get XMl e-arve file", "Saama XML e-arved kõik valitud arved", "Получить XML файл e-arve"],
    "Saama XML e-arved (SEB) kõik valitud arved": ["get XML file for SEB", "Saama XML e-arved (SEB) kõik valitud arved", "Получить XML для банка SEB"],
    "Saama XML e-arved (SWED) kõik valitud arved": ["get XML file for SWED", "Saama XML e-arved (SWED) kõik valitud arved", "Получить XML для банка SEB"],
    "Read kokku:": ["Rows total:", "Read kokku:", "Всего строк:"],
    "Summa kokku:": ["Summa total:", "Summa kokku:", "Сумма всего:"],
    "Jääk kokku:": ["Saldo total:", "Jääk kokku:", "Долг всего:"],
    "Kokku:":["Total:","Kokku:","Всего:"],
    "Määramata summa:":["Undefined summa:","Määramata summa:","Нераспределенная оплата:"],
    "Arved":["Bills","Arved","Счета"],
    "Viitenumber":["Reference","Viitenumber","Ссылка"],
    "Töötan": ["Working", "Töötan", "Работаю"],
    "Tekkis viga": ["Got error", "Tekkis viga", "Ошибка"],
    "Kas koosta SMK":["Create payment order?","Kas koosta SMK?","Создать платежное поручение?"],
    "Edukalt": ["Ok", "Edukalt", "Ок"],
    "Tekkis viga: kustutamine ebaõnnestus": ["Error, delete not success", "Tekkis viga: kustutamine ebaõnnestus", "Ошибка, удаление не прошло"]

}